extends Node2D

class Potion:
	var recipe = [0,0]
	var color
	var potionName = ""
	func _init(_recipe,_color, _potionName):
		recipe = _recipe
		color = _color
		potionName = _potionName

class Ingredient:
	var index = 0
	var position = [0,0]
	var ingredientName = ""
	func _init(_index,_position,_ingredientName):
		index = _index
		position = _position
		ingredientName = _ingredientName

var ingredients = [Ingredient.new(0,[2,3],"Glühwürmchen Sekret"), 
Ingredient.new(1,[4,-1],"Blut"), 
Ingredient.new(2,[0,0],"Mondblume"), 
Ingredient.new(3,[0,-3],"Rückenflosse einer Rotfeder"), 
Ingredient.new(4,[0,-2],"Fledermausflügel"), 
Ingredient.new(5,[2,-2],"Giftdrüse einer Schwarzen Witwe"), 
Ingredient.new(6,[-2,0],"Froschschenkel eines Grasfrosches")]

var potion_list = [
  Potion.new([0, -15], "color", "Verjüngungselixier"),
  Potion.new([0, -14], "color", "Phönixflammenelixier"),
  Potion.new([0, -13], "color", "Astralnebeltropfen"),
  Potion.new([-2, -12], "color", "Traumfängerelixier"),
  Potion.new([-2, -11], "color", "Unsichtbarkeitszaubertrank"),
  Potion.new([-2, -10], "color", "Schattenmeisterelixier"),
  Potion.new([-4, -9], "color", "Himmelsspäneelixier"),
  Potion.new([-4, -8], "color", "Zeitverzerrungstrank"),
  Potion.new([-4, -7], "color", "Dämonenflammenelixier"),
  Potion.new([-6, -6], "color", "Lebensfunkenelixier"),
  Potion.new([-6, -5], "color", "Glückskoboldtrank"),
  Potion.new([-8, -3], "color", "Traumweberelixier"),
  Potion.new([-8, -2], "color", "Morgentauelixier"),
  Potion.new([-10, 0], "color", "Nachtschleichertrank"),
  Potion.new([2, -14], "color", "Aurorastrahlenelixier"),
  Potion.new([2, -13], "color", "Weltenwandlerelixier"),
  Potion.new([0, -12], "color", "Silberflusselixier"),
  Potion.new([0, -11], "color", "Traumtänzerelixier"),
  Potion.new([0, -10], "color", "Schutzschildtrank"),
  Potion.new([-2, -9], "color", "Sternenklarheitstrank"),
  Potion.new([-2, -8], "color", "Schneewittchenelixier"),
  Potion.new([-2, -7], "color", "Elfenstaubelixier"),
  Potion.new([-4, -6], "color", "Schattenjägertrank"),
  Potion.new([-4, -5], "color", "Kristallkugeltrank"),
  Potion.new([-6, -4], "color", "Koboldgoldelixier"),
  Potion.new([-6, -3], "color", "Lichtfunkenelixier"),
  Potion.new([-6, -2], "color", "Sternenkreuzelixier"),
  Potion.new([-8, 0], "color", "Schatzsucherelixier"),
  Potion.new([4, -13], "color", "Golemgoldelixier"),
  Potion.new([2, -12], "color", "Wasserlaufelixier"),
  Potion.new([2, -11], "color", "Feenringelixier"),
  Potion.new([2, -10], "color", "Magische Rüstungstrank"),
  Potion.new([0, -9], "color", "Lichtspiegelelixier"),
  Potion.new([0, -8], "color", "Dämonenschildelixier"),
  Potion.new([0, -7], "color", "Flammenzauberelixier"),
  Potion.new([-2, -6], "color", "Seelenstärkungstrank"),
  Potion.new([-2, -5], "color", "Nebelschleierelixier"),
  Potion.new([-4, -4], "color", "Spiegelbildtrank"),
  Potion.new([-4, -3], "color", "Silberne Federelixier"),
  Potion.new([-4, -2], "color", "Morgensonneelixier"),
  Potion.new([-4, -1], "color", "Elfenwaldelixier"),
  Potion.new([-6, 0], "color", "Drachenherzelixier"),
  Potion.new([4, -12], "color", "Kristallregentropfen"),
  Potion.new([4, -11], "color", "Wolkennebeltrank"),
  Potion.new([4, -10], "color", "Zeitfaltentrank"),
  Potion.new([2, -9], "color", "Flüsterblitzelixier"),
  Potion.new([2, -8], "color", "Götternektartrank"),
  Potion.new([0, -6], "color", "Koboldjuweltrank"),
  Potion.new([0, -5], "color", "Sternenwindelixier"),
  Potion.new([-2, -4], "color", "Traumlichttrank"),
  Potion.new([-2, -3], "color", "Schattenmeisterelixier"),
  Potion.new([-2, -2], "color", "Traumtrank"),
  Potion.new([-2, -1], "color", "Funkenregenelixier"),
  Potion.new([-4, 0], "color", "Lebenselexier"),
  Potion.new([6, -12], "color", "Nebelwaldelixier"),
  Potion.new([6, -11], "color", "Lichtpfeiltrank"),
  Potion.new([4, -9], "color", "Sternenregentrunk"),
  Potion.new([2, -7], "color", "Silberkristalltrank"),
  Potion.new([2, -6], "color", "Schneeblumentrank"),
  Potion.new([2, -5], "color", "Elfenlächelnelixier"),
  Potion.new([0, -4], "color", "Dämonenabwehrelaixier"),
  Potion.new([0, -3], "color", "Götterfunkelexier"),
  Potion.new([0, -2], "color", "Zeitwächtertrank"),
  Potion.new([0, -1], "color", "Drachenflammenelixier"),
  Potion.new([-2, 0], "color", "Traumspiegelsaft"),
  Potion.new([-2, 1], "color", "Flüsterhauchelixier"),
  Potion.new([-2, 3], "color", "Morgentautrunk"),
  Potion.new([-4, 3], "color", "Schattenpfortentrunk"),
  Potion.new([6, -10], "color", "Koboldzauberelixier"),
  Potion.new([4, -8], "color", "Wolkenspringelixier"),
  Potion.new([4, -7], "color", "Nebelhauchelixier"),
  Potion.new([4, -6], "color", "Diamantschleiertropfen"),
  Potion.new([4, -5], "color", "Sternenlichtelixier"),
  Potion.new([2, -4], "color", "Herzklopfelixier"),
  Potion.new([2, -3], "color", "Träumendes Wasserelixier"),
  Potion.new([2, -2], "color", "Feuertänzerelixier"),
  Potion.new([2, -1], "color", "Regenbogenträumeelixier"),
  Potion.new([0, 0], "color", "Schlangenhautelixier"),
  Potion.new([0, 1], "color", "Nachtzaubertrank"),
  Potion.new([0, 2], "color", "Silberstreifelixier"),
  Potion.new([0, 3], "color", "Wolkenschleierelixier"),
  Potion.new([-2, 6], "color", "Drachenatemelixier"),
  Potion.new([8, -11], "color", "Elfenfeuerelixier"),
  Potion.new([6, -9], "color", "Sternenregentrank"),
  Potion.new([6, -8], "color", "Wolkentraumelixier"),
  Potion.new([6, -7], "color", "Sonnenscheinelixier"),
  Potion.new([6, -6], "color", "Traumfrostelixier"),
  Potion.new([4, -4], "color", "Feenlichtelixier"),
  Potion.new([4, -3], "color", "Glitzerschmetterlingstrank"),
  Potion.new([4, -2], "color", "Schattenblütenelixier"),
  Potion.new([2, 0], "color", "Koboldlächelnelixier"),
  Potion.new([2, 1], "color", "Dämonenstärkungstrank"),
  Potion.new([2, 2], "color", "Elfenrufelixier"),
  Potion.new([2, 3], "color", "Nebelzaubernebeltropfen"),
  Potion.new([0, 4], "color", "Kristallklangelixier"),
  Potion.new([0, 6], "color", "Sonnenspiegeltrank"),
  Potion.new([8, -10], "color", "Sternenstaubelixier"),
  Potion.new([8, -9], "color", "Blumenkönigstrank"),
  Potion.new([8, -8], "color", "Träumendeaugenelixier"),
  Potion.new([8, -7], "color", "Fledermausnachttrank"),
  Potion.new([6, -5], "color", "Tautropfenelixier"),
  Potion.new([6, -4], "color", "Schattenspieltrank"),
  Potion.new([6, -3], "color", "Geisterhauchelixier"),
  Potion.new([6, -2], "color", "Sonnentauelixier"),
  Potion.new([4, -1], "color", "Phönixliedelixier"),
  Potion.new([4, 0], "color", "Lichtschimmerelixier"),
  Potion.new([4, 1], "color", "Mondnebelelixier"),
  Potion.new([4, 2], "color", "Schattenflügeltrank"),
  Potion.new([2, 4], "color", "Glitzerschleierelixier"),
  Potion.new([2, 6], "color", "Wolkenzauberelixier"),
  Potion.new([10, -10], "color", "Mondnebelelixier"),
  Potion.new([10, -9], "color", "Kristallblütenelixier"),
  Potion.new([10, -8], "color", "Götterstimmetrank"),
  Potion.new([8, -6], "color", "Traumlandelixier"),
  Potion.new([8, -5], "color", "Nachtzauberschleierelixier"),
  Potion.new([8, -4], "color", "Froschsprungtrank"),
  Potion.new([8, -3], "color", "Geistergeheimnisselixier"),
  Potion.new([6, -1], "color", "Sternenmeerelixier"),
  Potion.new([6, 0], "color", "Sonnenblumenelixier"),
  Potion.new([6, 1], "color", "Feenpulverelixier"),
  Potion.new([4, 3], "color", "Elfenpfadtrank"),
  Potion.new([4, 4], "color", "Schattenwolfelixier"),
  Potion.new([4, 5], "color", "Koboldtraumelixier"),
  Potion.new([4, 6], "color", "Drachenkraftelixier"),
  Potion.new([12, -9], "color", "Diamantregentropfen"),
  Potion.new([12, -8], "color", "Wolkenlichttrank"),
  Potion.new([10, -7], "color", "Silberne Federelixier"),
  Potion.new([10, -6], "color", "Morgenschauerelixier"),
  Potion.new([10, -5], "color", "Nebelherzenelixier"),
  Potion.new([10, -4], "color", "Sternenfeuerelixier"),
  Potion.new([10, -3], "color", "Seelenliederelixier"),
  Potion.new([10, -2], "color", "Feuervogelelixier"),
  Potion.new([10, -1], "color", "Mondtanzelixier"),
  Potion.new([8, 4], "color", "Schattenpfadtrank"),
  Potion.new([8, 5], "color", "Göttertränenelixier"),
  Potion.new([8, 7], "color", "Elfenstaubelixier"),
  Potion.new([6, 9], "color", "Traumhüterelixier"),
  Potion.new([18, -6], "color", "Silberfunkentrunk"),
  Potion.new([16, -6], "color", "Nebelblumenelixier"),
  Potion.new([16, -4], "color", "Zauberschleiertrank"),
  Potion.new([14, -3], "color", "Sternenherzenelixier"),
  Potion.new([14, -2], "color", "Lichtzauberelixier"),
  Potion.new([12, 0], "color", "Seelenlichttrank"),
  Potion.new([12, 1], "color", "Wolkenhauchelixier"),
  Potion.new([12, 2], "color", "Koboldkristalltrank"),
  Potion.new([10, 4], "color", "Diamantschattenelixier"),
  Potion.new([10, 5], "color", "Drachenflugelixier"),
  Potion.new([10, 6], "color", "Elfenfeuerelixier"),
  Potion.new([8, 8], "color", "Sternenregentrank"),
  Potion.new([8, 9], "color", "Wolkentraumelixier"),
  Potion.new([6, 12], "color", "Sonnenscheinelixier"),
  Potion.new([18, -1], "color", "Traumfrostelixier"),
  Potion.new([16, -2], "color", "Feenlichtelixier"),
  Potion.new([14, 0], "color", "Glitzerschmetterlingstrank"),
  Potion.new([16, 3], "color", "Schattenblütenelixier"),
  Potion.new([14, 2], "color", "Koboldlächelnelixier"),
  Potion.new([12, 4], "color", "Dämonenstärkungstrank"),
  Potion.new([14, 7], "color", "Elfenrufelixier"),
  Potion.new([12, 6], "color", "Zeitwellenelixier"),
  Potion.new([10, 8], "color", "Schneeflöckchentrank"),
  Potion.new([12, 11], "color", "Sternentorelixier"),
  Potion.new([10, 10], "color", "Schattenflügeltrank"),
  Potion.new([8, 10], "color", "Glitzerschleierelixier"),
  Potion.new([8, 12], "color", "Wolkenzauberelixier"),
  Potion.new([10, 15], "color", "Mondnebelelixier")
]

var inventory = [0,0,0,0,0,0,0]

var moonPhase = 0

# Called when the node enters the scene tree for the first time.
func _ready():
	pass


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	if Input.is_action_pressed("ui_cancel"):
		get_tree().quit()
